id: I33F0C411
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T13:17:01+00:00'
last_modified: '2022-06-07T12:22:16.837371+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20846
  title: བྱ་ཁྱུང་གདན་རབས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    74C1:
      image_group_id: I1GS52249
      title: Volume 1 of bya khyung gdan rabs
      total_pages: 163
      order: 1
      base_file: 74C1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
