id: P000578
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20846
  title: བྱ་ཁྱུང་གདན་རབས
  author: ''
  volumes:
    3e366a074cf243baa8f62bb87ff2c42a:
      image_group_id: I1GS52249
      title: Volume 1 of bya khyung gdan rabs
      volume_number: 1
      total_pages: 163
      base_file: v001.txt
